version: '2'
services:

  server:
    image: "cda0/k3s:v1.18.2-k3s1-amd64"
    command: server --tls-san 192.168.1.12 --disable traefik --disable local-storage
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_TOKEN=$K3S_TOKEN
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
    ports:
    - 6443:6443
    - 80:80
    - 443:443

  agent:
    image: "cda0/k3s:v1.18.2-k3s1-amd64"
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_TOKEN=$K3S_TOKEN

volumes:
  k3s-server:
    driver: local
