---
- name: Install k3s in docker
  hosts: all
  connection: local
  roles:
    - { role: docker-compose, tags: ['docker-compose'] }
    - { role: get-kubeconfig, tags: ['kubeconfig'] }
    - { role: metallb, tags: ['metallb'] }
    - { role: nginx, tags: ['nginx'] }
    # - { role: drone, tags: ['drone'] }
