name: name
latitude: 0
longitude: 0
elevation: 0

base_url: homeassistant.example.com

db_url: sqlite:////home/user/.homeassistant/test

api_password: 0000000000000000
trusted_ip: 0.0.0.0/24
trusted_proxy: 0.0.0.0

tado_username: tado@example.com
tado_password: password
tado_home_id: 000000

hue_ip_address: 0.0.0.0

sonos_play_1: 0.0.0.0
sonos_play_3: 0.0.0.0
sonos_playbar: 0.0.0.0

roku_living_room_ip: 0.0.0.0

cast_living_room_ip: 0.0.0.0
cast_lounge_ip: 0.0.0.0

pihole_host: 0.0.0.0
pihole_api_key: 000000000000000000000000000000000000000

openweathermap_api_key: 00000000000000000000000

gitlab_id: 00000000
gitlab_token: 00000000000000000000