- id: lights_on_at_sunset
  alias: 'Turn lights on at sunset'
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 1.5
  action:
    service: light.turn_on
    entity_id:
      - group.living_room
      - light.console_table