---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
stringData:
  root-password: changeme
  myuser-password: changeme
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data:
  my.cnf: |-
    # The MariaDB configuration file
    #
    # The MariaDB/MySQL tools read configuration files in the following order:
    # 1. "/etc/mysql/mariadb.cnf" (this file) to set global defaults,
    # 2. "/etc/mysql/conf.d/*.cnf" to set global options.
    # 3. "/etc/mysql/mariadb.conf.d/*.cnf" to set MariaDB-only options.
    # 4. "~/.my.cnf" to set user-specific options.
    #
    # If the same option is defined multiple times, the last one will apply.
    #
    # One can use all long options that the program supports.
    # Run program with --help to get a list of available options and with
    # --print-defaults to see which it would actually understand and use.

    #
    # This group is read both by the client and the server
    # use it for options that affect everything
    #
    [client-server]

    #socket                  = /run/mysqld/mysqld.sock
    port                   = 3306

    # Import all .cnf files from configuration directory
    !includedir /etc/mysql/conf.d/
    !includedir /etc/mysql/mariadb.conf.d/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: myuser-password
        - name: MYSQL_USER
          value: myuser
        volumeMounts:
        - name: nfs
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: config-volume
          mountPath: /etc/mysql/my.cnf
          subPath: my.cnf
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfspvc
      - name: config-volume
        configMap:
          name: mariadb-config
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: default
spec:
  ports:
  - name: http
    port: 3306
    protocol: TCP
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
        - name: phpmyadmin
          containerPort: 80
        env:
        - name: PMA_HOST
          value: mariadb-service
        - name: PMA_PORT
          value: "3306"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secrets
              key: root-password
        volumeMounts:
        - name: nfs
          mountPath: /mnt
          subPath: phpmyadmin
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfspvc
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: phpmyadmin
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: phpmyadmin-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: phpmyadmin.k3s.magiccastle.me.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: phpmyadmin-service
          servicePort: http
