---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions: ["vers=4"]
  nfs:
    path: /k3s
    server: 192.168.1.12
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfspvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "slow"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsmedia
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions: ["vers=4"]
  nfs:
    path: /media
    server: 192.168.1.12
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsmedia
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: "slow"
  resources:
    requests:
      storage: 1Mi
