apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.name }}-service
          servicePort: http
