apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: default
spec:
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    protocol: TCP
  - name: ssh
    port: {{ .Values.sshPort }}
    targetPort: 22
    protocol: TCP
  selector:
    app: {{ .Values.name }}
